server:
  port: 10085
  servlet:
   contextPath: /im
spring:
  application:
    name: WEBIM
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/D:/H2/WEBIM
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.128.32:3306/webim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: webim
    password: webim
    dbcp2:
      max-wait-millis: 10000
      max-idle: 15
      initial-size: 10
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8
  flyway:
    enabled: true
    locations: classpath:migration/mysql
  servlet:
   multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB
framework:
  app:
    home: /Projects/RunData/webim_home
  ip:
    enable: true
    system-enable: true
    topoptid: WebIm
    home: http://192.168.134.2:11000/framework/system
    auth-enable: false
    usercode: admin
    password: 000000
  jdbcplatform:
    url: jdbc:oracle:thin:@192.168.137.95:1521:orcl
    username: framework
    password: framework
webim:
  robot:
    type: es
    max-answer: 4
  elastic-search:
    os-id: WEB_IM_SVR
    server-host-ip: 127.0.0.1
    server-host-port: 9200
    cluster-name: elasticsearch
    min-score: 0.5
  file-store:
    base-dir: /Projects/RunData/webim_home/upload
  sms:
    send-url: http://218.94.123.217:8998/service/sendMsg
  notify:
    type: none

